meta_product_name: "Sports Companion"
meta_title: "Sports Companion - A sports guide for sports fans"
meta_description: "A perfect guide for your sports knowledge needs"
meta_image: "blackandwhite.png" # should exist in `app/assets/images/`
